# Generated by Django 4.0.6 on 2022-07-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_ticket_ticknum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticknum',
        ),
    ]
