# Generated by Django 4.0.6 on 2022-07-17 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_ticket_ticknum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='fileupload',
            new_name='file_Upload',
        ),
    ]
